{% set name = "squashfuse" %}
{% set version = "0.5.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/vasi/squashfuse/releases/download/{{ version }}/squashfuse-{{ version }}.tar.gz
  sha256: 54e4baaa20796e86a214a1f62bab07c7c361fb7a598375576d585712691178f5

build:
  number: 2
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - pkg-config
    - make
  host:
    - libfuse 3.*
    - zlib
    - liblzma-devel
    - lz4-c
    - lzo
    - zstd

test:
  commands:
    - test -f $PREFIX/bin/squashfuse
    - test -f $PREFIX/bin/squashfuse_ll
    - test -f $PREFIX/lib/libsquashfuse${SHLIB_EXT}
    - test ! -f $PREFIX/lib/libsquashfuse.a

about:
  home: https://github.com/vasi/squashfuse
  license: BSD-2-Clause
  license_file: LICENSE
  summary: FUSE filesystem to mount squashfs archives

extra:
  recipe-maintainers:
    - xhochy
