{% set name = "squashfuse" %}
{% set version = "0.6.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/vasi/squashfuse/releases/download/{{ version }}/squashfuse-{{ version }}.tar.gz
  sha256: 0c9f582ca488dc5eb450830d72f45a042ef5c0476118502ab5ed86ae9dd8bd46

build:
  number: 0
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - pkg-config
    - make
  host:
    - libfuse3
    - zlib
    - liblzma-devel
    - lz4-c
    - lzo
    - zstd

test:
  commands:
    - test -f $PREFIX/bin/squashfuse
    - test -f $PREFIX/bin/squashfuse_ll
    - test -f $PREFIX/lib/libsquashfuse${SHLIB_EXT}
    - test ! -f $PREFIX/lib/libsquashfuse.a

about:
  home: https://github.com/vasi/squashfuse
  license: BSD-2-Clause
  license_file: LICENSE
  summary: FUSE filesystem to mount squashfs archives

extra:
  recipe-maintainers:
    - xhochy
