{% set name = "squashfuse" %}
{% set version = "0.6.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/vasi/squashfuse/releases/download/{{ version }}/squashfuse-{{ version }}.tar.gz
  sha256: 267f2852d6e20147eb1e21931f9d0fe7634a66612f1ede27e15fa60e56ce0eac

build:
  number: 0
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - pkg-config
    - make
  host:
    - libfuse3
    - zlib
    - liblzma-devel
    - lz4-c
    - lzo
    - zstd

test:
  commands:
    - test -f $PREFIX/bin/squashfuse
    - test -f $PREFIX/bin/squashfuse_ll
    - test -f $PREFIX/lib/libsquashfuse${SHLIB_EXT}
    - test ! -f $PREFIX/lib/libsquashfuse.a

about:
  home: https://github.com/vasi/squashfuse
  license: BSD-2-Clause
  license_file: LICENSE
  summary: FUSE filesystem to mount squashfs archives

extra:
  recipe-maintainers:
    - xhochy
